# Generated by Django 5.0.6 on 2024-06-17 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_hospital_id'),
        ('laboratory', '0009_alter_diagnosisreport_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital_id',
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='laboratory.hospital'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superuser', 'Superuser'), ('staff', 'Staff'), ('doctor', 'Doctor'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
