# Generated by Django 5.0.6 on 2024-06-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_medicalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('medical_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.medicalimage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.doctor')),
            ],
        ),
    ]
