# Generated by Django 5.0.6 on 2024-06-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_remove_hospital_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='diagnosisreport',
            old_name='report_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='diagnosisreport',
            old_name='diagnosis',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='diagnosisreport',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='diagnosisreport',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalimage',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='laboratory.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosisreport',
            name='medical_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_report', to='laboratory.medicalimage'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
