# Generated by Django 5.0.6 on 2024-06-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_remove_diagnosisreport_medical_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiagnosisReportImage',
            new_name='DiagnosisReportImages',
        ),
    ]
