# Generated by Django 5.0.6 on 2024-06-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_rename_diagnosisreportimage_diagnosisreportimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_datas', to='laboratory.patient'),
        ),
        migrations.AlterField(
            model_name='medicaldataimages',
            name='medical_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='laboratory.medicaldata'),
        ),
    ]
