# Generated by Django 5.0.6 on 2024-06-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_remove_hospital_admins_alter_hospital_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisreport',
            name='medical_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_report', to='laboratory.medicaldata'),
        ),
    ]
