# Generated by Django 5.0.6 on 2024-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_alter_diagnosisreport_medical_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisreportimages',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
